import day8
import gleeunit/should

// pub fn day8_solve_test() {
//   "............
// ........0...
// .....0......
// .......0....
// ....0.......
// ......A.....
// ............
// ............
// ........A...
// .........A..
// ............
// ............"
//   |> day8.solve_a
//   |> should.equal(14)
// }

pub fn day8_solve_b_test() {
  "T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........
"
  |> day8.solve_b
  |> should.equal(9)
}
// pub fn day8_solve_real_test() {
//   let assert Ok(in) = simplifile.read(from: "test/inputs/day8")
//
//   in
//   |> day8.solve_a
//   |> io.debug
// }

// pub fn day8_solve_real_test() {
//   let assert Ok(in) = simplifile.read(from: "test/inputs/day8")
//
//   in
//   |> day8.solve_b
//   |> io.debug
// }
