import day7
import day8
import gleam/io
import gleeunit/should
import simplifile

pub fn day8_solve_test() {
  "............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"
  |> day8.solve
  |> io.debug
}

pub fn day8_solve_real_test() {
  let assert Ok(in) = simplifile.read(from: "test/inputs/day8")

  in
  |> day8.solve
  |> io.debug
}
